## IQR = Q3 - Q1 (Q -> Quartile)

In [5]:
import pandas as pd

df = pd.read_csv('heights_IQR.csv')
df

       name  height
0     mohan     1.2
1     maria     2.3
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5
16   donald     7.1
17    aamir    14.5
18      ken    23.2
19      Liu    40.2

In [6]:
df.describe()

          height
count  20.000000
mean    8.390000
std     8.782812
min     1.200000
25%     5.350000
50%     5.700000
75%     6.275000
max    40.200000

In [7]:
Q1 = df.height.quantile(0.25)
Q3 = df.height.quantile(0.75)
Q1, Q3

(np.float64(5.3500000000000005), np.float64(6.275))

In [18]:
IQR = Q3 - Q1
IQR

np.float64(0.9249999999999998)

In [19]:
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q1 + 1.5 * IQR
lower_limit, upper_limit

(np.float64(3.962500000000001), np.float64(6.737500000000001))

In [20]:
# Outliers
df[(df.height < lower_limit) | (df.height > upper_limit)]

      name  height
0    mohan     1.2
1    maria     2.3
16  donald     7.1
17   aamir    14.5
18     ken    23.2
19     Liu    40.2

In [22]:
df_no_outlier = df[(df.height > lower_limit) & (df.height < upper_limit)]
df_no_outlier

       name  height
2     sakib     4.9
3       tao     5.1
4     virat     5.2
5    khusbu     5.4
6    dmitry     5.5
7    selena     5.5
8      john     5.6
9     imran     5.6
10     jose     5.8
11  deepika     5.9
12   yoseph     6.0
13    binod     6.1
14  gulshan     6.2
15  johnson     6.5