# Titanic Survival Prediction

### Data Cleaning, Preprocessing and Filling

In [125]:
import pandas as pd

df1 = pd.read_csv('train.csv')
df2 = pd.read_csv('test.csv')
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [126]:
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [127]:
df1.shape

(891, 12)

In [128]:
df1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [129]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [130]:
df2.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [131]:
df1.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)
df2.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)

In [132]:
df1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked'],
      dtype='object')

In [133]:
df2.columns

Index(['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [134]:
df1['familySize'] = df1['SibSp'] + df1['Parch'] + 1
df2['familySize'] = df2['SibSp'] + df2['Parch'] + 1

In [135]:
df1.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,familySize
0,1,0,3,male,22.0,1,0,7.2500,S,2
1,2,1,1,female,38.0,1,0,71.2833,C,2
2,3,1,3,female,26.0,0,0,7.9250,S,1
3,4,1,1,female,35.0,1,0,53.1000,S,2
4,5,0,3,male,35.0,0,0,8.0500,S,1

In [136]:
df2.head()

,PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,familySize
0,892,3,male,34.5,0,0,7.8292,Q,1
1,893,3,female,47.0,1,0,7.0000,S,2
2,894,2,male,62.0,0,0,9.6875,Q,1
3,895,3,male,27.0,0,0,8.6625,S,1
4,896,3,female,22.0,1,1,12.2875,S,3

In [137]:
df1.drop(['SibSp','Parch'],axis=1,inplace=True)
df2.drop(['SibSp','Parch'],axis=1,inplace=True)

In [138]:
df1.head()

   PassengerId  Survived  Pclass     Sex   Age     Fare Embarked  familySize
0            1         0       3    male  22.0   7.2500        S           2
1            2         1       1  female  38.0  71.2833        C           2
2            3         1       3  female  26.0   7.9250        S           1
3            4         1       1  female  35.0  53.1000        S           2
4            5         0       3    male  35.0   8.0500        S           1

In [139]:
df1['Sex'] = df1['Sex'].replace({'male': 0, 'female': 1})
df2['Sex'] = df2['Sex'].replace({'male': 0, 'female': 1})

C:\Users\rosha\AppData\Local\Temp\ipykernel_1764\538482799.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Sex'] = df1['Sex'].replace({'male': 0, 'female': 1})
C:\Users\rosha\AppData\Local\Temp\ipykernel_1764\538482799.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Sex'] = df2['Sex'].replace({'male': 0, 'female': 1})

In [140]:
df1.head()

   PassengerId  Survived  Pclass  Sex   Age     Fare Embarked  familySize
0            1         0       3    0  22.0   7.2500        S           2
1            2         1       1    1  38.0  71.2833        C           2
2            3         1       3    1  26.0   7.9250        S           1
3            4         1       1    1  35.0  53.1000        S           2
4            5         0       3    0  35.0   8.0500        S           1

In [141]:
df2.head()

   PassengerId  Pclass  Sex   Age     Fare Embarked  familySize
0          892       3    0  34.5   7.8292        Q           1
1          893       3    1  47.0   7.0000        S           2
2          894       2    0  62.0   9.6875        Q           1
3          895       3    0  27.0   8.6625        S           1
4          896       3    1  22.0  12.2875        S           3

In [142]:
df1['Embarked'] = df2['Embarked'].fillna(df2['Embarked'].mode()[0])
df2['Embarked'] = df2['Embarked'].fillna(df2['Embarked'].mode()[0])

In [143]:
df1.head()

   PassengerId  Survived  Pclass  Sex   Age     Fare Embarked  familySize
0            1         0       3    0  22.0   7.2500        Q           2
1            2         1       1    1  38.0  71.2833        S           2
2            3         1       3    1  26.0   7.9250        Q           1
3            4         1       1    1  35.0  53.1000        S           2
4            5         0       3    0  35.0   8.0500        S           1

In [145]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            473
Fare             0
Embarked       473
familySize       0
dtype: int64

In [146]:
df2.isnull().sum()

PassengerId     0
Pclass          0
Sex             0
Age            86
Fare            1
Embarked        0
familySize      0
dtype: int64

In [147]:
df2['Fare'] = df2['Fare'].fillna(df2['Fare'].median())

In [148]:
df2.head()

   PassengerId  Pclass  Sex   Age     Fare Embarked  familySize
0          892       3    0  34.5   7.8292        Q           1
1          893       3    1  47.0   7.0000        S           2
2          894       2    0  62.0   9.6875        Q           1
3          895       3    0  27.0   8.6625        S           1
4          896       3    1  22.0  12.2875        S           3

In [149]:
df1['Age'] = df1['Age'].fillna(df1['Age'].median())
df2['Age'] = df2['Age'].fillna(df2['Age'].median())

In [152]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Embarked'] = le.fit_transform(df1['Embarked'])

In [153]:
df1.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       0
familySize     0
dtype: int64

In [154]:
df2.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       0
familySize     0
dtype: int64

In [163]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Embarked'] = le.fit_transform(df1['Embarked'])
df2['Embarked'] = le.fit_transform(df2['Embarked'])

In [164]:
df1.head()

   PassengerId  Survived  Pclass  Sex   Age     Fare  Embarked  familySize
0            1         0       3    0  34.5   7.2500         1           2
1            2         1       1    1  47.0  71.2833         2           2
2            3         1       3    1  62.0   7.9250         1           1
3            4         1       1    1  27.0  53.1000         2           2
4            5         0       3    0  22.0   8.0500         2           1

In [165]:
df2.head()

   PassengerId  Pclass  Sex   Age     Fare  Embarked  familySize
0          892       3    0  34.5   7.8292         1           1
1          893       3    1  47.0   7.0000         2           2
2          894       2    0  62.0   9.6875         1           1
3          895       3    0  27.0   8.6625         2           1
4          896       3    1  22.0  12.2875         2           3

In [166]:
X = df1.drop('Survived',axis=1)
y = df1['Survived']

In [167]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

In [168]:
X_train.shape

(712, 7)

In [169]:
X_test.shape

(179, 7)

### Model Training

In [170]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.770949720670391

### Prediction

In [171]:
predictions = model.predict(df2)

output = pd.DataFrame({'PassengerId': df2.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [173]:
output.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1